name: flutter_multi_package_playground

workspace:
  # apps
  - apps/

  # domain & data
  - domain/
  - data/

  # core
  - core/common/
  - core/entity/
  - core/response/
  - core/code_analyzer/

  # shared
  - shared/designsystem/
  - shared/ui/
  - shared/localization/
  - shared/navigation/
  - shared/di/

  # features
  - features/auth/login/
  - features/auth/signup/
  - features/auth/splash/
  - features/auth/onboarding/
  - features/auth/setting/
  - features/auth/profile/
  - features/auth/change_password/
  - features/auth/notification/
  - features/auth/forgot_password/
  - features/auth/otp_verification/

  - features/posts/home/
  - features/posts/create_post/
  - features/posts/post_details/

environment:
  sdk: ^3.11.4

dev_dependencies:
  melos: ^7.5.1

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.11.4

      dependencies:
        common: ^0.0.1
        database: ^0.0.1
        secured: ^0.0.1
        sharedpref: ^0.0.1
        domain: ^0.0.1
        designsystem: ^0.0.1
        ui: ^0.0.1
        di: ^0.0.1
        navigation: ^0.0.1
        entity: ^0.0.1
        response: ^0.0.1
        data: ^0.0.1
        code_analyzer: ^0.0.1
        localization: ^0.0.1

        flutter_bloc: ^9.1.1
        get_it: ^9.2.1
        cupertino_icons: ^1.0.9
        shared_preferences: ^2.5.5
        equatable: ^2.0.8
        flutter_svg: ^2.2.4
        formz: ^0.8.0
        dio: ^5.9.2
        jiffy: ^6.4.4
        fluttertoast: ^9.0.0
        image_picker: ^1.2.1
        url_launcher: ^6.3.2
        webview_flutter: ^4.13.1
        json_annotation: ^4.11.0
        envied: ^1.3.4
        flutter_local_notifications: ^21.0.0
        intl: ^0.20.2
        freezed: ^3.2.5
        freezed_annotation: ^3.1.0
        carousel_slider: ^5.1.2
        flutter_screenutil: ^5.9.3
        lottie: ^3.3.2
        font_awesome_flutter: ^11.0.0
        flutter_widget_from_html: ^0.17.2
        logger: ^2.7.0
        yaml_edit: ^2.2.4
        go_router: ^17.2.0
        flutter_inappwebview: ^6.1.5
        background_downloader: ^9.5.4
        rxdart: ^0.28.0
        flutter_html: ^3.0.0
        firebase_core: ^4.6.0
        firebase_messaging: ^16.1.3
        firebase_crashlytics: ^5.1.0
        firebase_analytics: ^12.2.0
        #firebase_remote_config: ^6.3.0
        clarity_flutter: ^1.7.1
        in_app_update: ^4.2.5
        package_info_plus: ^9.0.1
        cached_network_image: ^3.4.1
        flutter_secure_storage: ^10.0.0
        flutter_image_compress: ^2.4.0
        path: ^1.9.1
        path_provider: ^2.1.5
        sqflite: ^2.4.2
        permission_handler: ^12.0.1

      dev_dependencies:
        flutter_test:
          sdk: flutter
        flutter_lints: ^6.0.0
        dart_code_linter: ^4.0.2
        melos: ^7.5.1
        json_serializable: ^6.13.1
        build_runner: ^2.13.1
        envied_generator: ^1.3.4
        intl_utils: ^2.8.14
        mockito: ^5.6.4

  scripts:
    analyze:
      run: melos exec -- flutter analyze

    clean_and_get:
      run: melos exec -- flutter clean && melos bootstrap
      description: Cleans and then fetches dependencies for all packages.

    # generate:barrels:
    #   run: dart run melos_scripts/barrel_generator.dart
    #   description: Update all package barrel files

    update_overrides:
      run: melos exec -- dart run $(pwd)/scripts/pubspec_overrides.dart && melos
        bootstrap

    outdated:
      description: Check outdated dependencies in all Flutter packages
      exec: flutter pub outdated
      packageFilters:
        flutter: true

    outdated:all:
      description: Check all packages, including pure Dart packages
      steps:
        - melos run outdated --no-select
        - melos exec --no-private -- "dart pub outdated"

    env_secret_generate:
      run: melos exec --scope secret_env -- dart run build_runner build

    build_runner: |
      melos exec -c 1 --scope="domain" --scope="response" --scope="localization" -- \
        flutter pub run build_runner build --delete-conflicting-outputs

    build_runner_feature:
      description: Run build_runner for feature packages only
      exec: flutter pub run build_runner build --delete-conflicting-outputs
      packageFilters:
        tags:
          - feature
        dependsOn: build_runner

    locale_gen:
      run: melos exec --scope localization -- flutter gen-l10n

    update_minor_deps:
      description: Update minor dependencies
      run: dart run melos_minor_deps_update.dart

    update_major_deps:
      description: Update major dependencies
      run: dart run melos_major_deps_update.dart

    # Production APK builds
    build:apk:production:release:
      run: melos exec --scope="app" -- flutter build apk --target=lib/main.dart
        --flavor production --release
      description: Build production APK (release mode)

    # Development APK builds
    build:apk:development:release:
      run: melos exec --scope="app" -- flutter build apk --target=lib/main.dart
        --flavor development --release
      description: Build development APK (release mode)
