name: localization
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  code_analyzer: ^0.0.1
  common: ^0.0.1
  pref_storage: ^0.0.1

  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dart_code_linter: ^4.1.7
  intl_utils: 2.8.14
  build_runner: ^2.15.0

flutter:
  generate: true
