name: splash
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

melos:
  tags:
    - feature

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  navigation: ^0.0.1
  designsystem: ^0.0.1
  ui: ^0.0.1

  go_router: ^17.2.0
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
